name: Build ESP32 Firmware

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: espressif/idf:release-v4.4

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: |
          cd esp32_nat_router
          idf.py build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: firmware
          path: |
            esp32_nat_router/build/*.bin
            esp32_nat_router/build/bootloader/*.bin
